name: Release Package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Compile TypeScript
        uses: iCrawl/action-tsc@v1
      - name: List Files
        run: ls -la
