name: Release Package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Install Packages
        run: npm install
      - name: Compile TypeScript
        run: npm build
      - name: List Files
        run: ls -la
